/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Account: typeof import('./src/components/Account.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    BabylonScene: typeof import('./src/components/BabylonScene.vue')['default']
    Countdown: typeof import('./src/components/Countdown.vue')['default']
    Experiences: typeof import('./src/components/Experiences.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MainComponent: typeof import('./src/components/MainComponent.vue')['default']
    Meeting: typeof import('./src/components/Meeting.vue')['default']
    MeetingModal: typeof import('./src/components/MeetingModal.vue')['default']
    Meetings: typeof import('./src/components/Meetings.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RoomModal: typeof import('./src/components/RoomModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    UserModal: typeof import('./src/components/UserModal.vue')['default']
  }
}
